artifacts: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/blob/main/winequality-data.zip
  local_date_file: artifacts/data_ingestion/date.zip
  unzip_dir: artifacts/data_ingestion
